### ISSUE TITLE
Create an architecture diagram for the system

### ISSUE THREAD

**Issue by SayaliNilangekar** [gopinathsjsu/team-project-team-six#1]

**Comment by impratik7** [comment]
Crated initial architecture diagram based on discussed tech stack.

Frontend: ReactJS
Backend: Java
Database: MySQL
REST API: Postman(Testing APIs)
Cloud: AWS EC2

**Comment by impratik7** [comment]
Architecture diagram available at https://drive.google.com/file/d/1tcxZSMzyiPKqEBDM2QKGEVvvioQredKV/view?usp=sharing
