### ISSUE TITLE
Add POST/UPDATE/GET APIs for Airline

### ISSUE THREAD

**Issue by SayaliNilangekar** [gopinathsjsu/team-project-team-six#34]

**Comment by impratik7** [comment]
Created /create-airline api.


![Image](https://user-images.githubusercontent.com/38047130/204080245-4bff057c-ca82-4482-8103-96b9264d64b6.png)

**Comment by impratik7** [comment]
Reflected in RDS


![Image](https://user-images.githubusercontent.com/38047130/204080280-10ba1970-d1b0-4391-8fea-84bc820bac23.png)

**Comment by impratik7** [comment]
Created /get-airline api


![Image](https://user-images.githubusercontent.com/38047130/204408568-9a279360-af83-4c2c-b42c-d50eb371e028.png)
