### ISSUE TITLE
Create a database on RDS

### ISSUE THREAD

**Issue by Ashutoshp15** [gopinathsjsu/team-project-team-six#9]

**Comment by impratik7** [comment]
Created RDS instance on AWS:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'airport',
        'USER': 'admin',
        'PASSWORD': '',
        'HOST': 'airportmngt6.cdqv1aao9478.us-west-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}
